# Redis
redis:
  host: "127.0.0.1"
  port: 6379
  password: '123456'

mysql:
  host: "127.0.0.1"
  port: 3306
  user: 'root'
  password: 'root123456'
  db: 'swbitcasb'

ethBlock: 'ETH_BLOCK'
ethBlockList: 'ETH_BLOCK_LIST'

# 以太坊地址
ethUrl: 'https://cloudflare-eth.com'
# 钱包池
WalletPools: 'ETH_WALLET_POOLS'
# 匹配成功的区块信息
MatchedBlocks: 'MATCHED_BLOCKS'
# 订单状态
order_state: "ORDER_STATE"